from __future__ import annotations

from gory_core.role_payloads import DEFAULT_API_ROLE, SUPPORTED_API_ROLES


def build_api_docs() -> dict:
    roles = sorted(SUPPORTED_API_ROLES)
    return {
        "name": "GORI Public API",
        "defaultRole": DEFAULT_API_ROLE,
        "canonicalPaths": {
            "zoneDecision": "/api/zones/{zoneId}/decision",
            "legacyZoneDecision": "/api/decision/{zone_id}",
        },
        "glossary": {
            "status": "Current incident status derived from signal context.",
            "lifecycleState": "Explainable lifecycle stage over time.",
            "severityLevel": "Explainable incident severity classification.",
            "canonicalId": "Stable incident identity used across time and persistence.",
            "zoneId": "Affected zone identifier used to retrieve zone decision context.",
        },
        "consumerFlows": {
            "operator": {
                "operatorFlow": [
                    "List active incidents",
                    "Open incident detail",
                    "Inspect severity, lifecycle, spread and cross-confirmation",
                    "Inspect retained incident history",
                    "Open affected zone decision context",
                ],
                "requiredEndpoints": [
                    "/api/incidents?role=operator",
                    "/api/incidents/{canonicalId}?role=operator",
                    "/api/incidents/{canonicalId}/history?role=operator",
                    "/api/zones/{zoneId}/decision?role=operator",
                ],
                "contract": {
                    "incidentListCard": [
                        "canonicalId",
                        "zoneId",
                        "status",
                        "severityLevel",
                        "lifecycleState",
                        "location",
                        "lastUpdatedAt",
                    ],
                    "incidentDetail": [
                        "canonicalId",
                        "zoneId",
                        "runtimeIncidentId",
                        "status",
                        "severityLevel",
                        "lifecycleState",
                        "sources",
                        "signalsCount",
                        "timelineSummary",
                    ],
                    "zoneDecision": [
                        "zone",
                        "risk",
                        "incident",
                        "spread",
                        "crossConfirmation",
                        "routing",
                        "history",
                    ],
                },
            }
        ,
            "operatorDashboard": {
                "sections": [
                    "Dashboard Home / Overview",
                    "Incident Detail View",
                    "Zone Decision Context View",
                    "Situational Summary Cards",
                    "Secondary Situational Panel",
                ],
                "requiredEndpoints": [
                    "/api/incidents?role=operator",
                    "/api/incidents/{canonicalId}?role=operator",
                    "/api/incidents/{canonicalId}/history?role=operator",
                    "/api/zones/{zoneId}/decision?role=operator",
                    "/api/operator/summary",
                ],
                "views": {
                    "DashboardHome": {
                        "purpose": [
                            "Show how many active incidents exist",
                            "Show which incidents need attention first",
                            "Show where spread pressure is elevated",
                        ],
                        "sections": {
                            "summaryCards": {
                                "endpoint": "/api/operator/summary",
                                "model": "SituationalCards",
                                "essentialFields": [
                                    "activeIncidentsCount",
                                    "criticalIncidentsCount",
                                    "zonesWithElevatedSpread",
                                    "operatorAttentionCount",
                                ],
                                "optionalFields": [],
                            },
                            "incidentList": {
                                "endpoint": "/api/incidents?role=operator",
                                "model": "IncidentListItem",
                                "essentialFields": [
                                    "canonicalId",
                                    "zoneId",
                                    "zoneLabel",
                                    "incidentPriority",
                                    "status",
                                    "lifecycleState",
                                    "severityLevel",
                                    "spreadPressure",
                                    "lastUpdatedAt",
                                ],
                                "optionalFields": [],
                            },
                            "situationalStrip": {
                                "endpoint": "/api/incidents?role=operator",
                                "model": "IncidentListItem",
                                "essentialFields": [
                                    "severityLevel",
                                    "lifecycleState",
                                    "zoneLabel",
                                ],
                                "optionalFields": ["lastUpdatedAt"],
                            },
                        },
                    },
                    "IncidentDetailView": {
                        "purpose": [
                            "Explain what is happening",
                            "Show incident severity, lifecycle and support",
                            "Link the operator to the affected zone context",
                        ],
                        "sections": {
                            "header": {
                                "endpoint": "/api/incidents/{canonicalId}?role=operator",
                                "model": "IncidentDetailView",
                                "essentialFields": [
                                    "canonicalId",
                                    "zoneId",
                                    "zoneLabel",
                                    "severityLevel",
                                    "lifecycleState",
                                    "status",
                                ],
                                "optionalFields": ["runtimeIncidentId"],
                            },
                            "supportSummary": {
                                "endpoint": "/api/incidents/{canonicalId}?role=operator",
                                "model": "IncidentDetailView",
                                "essentialFields": ["sources", "signalsCount"],
                                "optionalFields": ["timelineSummary"],
                            },
                            "historySummary": {
                                "endpoint": "/api/incidents/{canonicalId}/history?role=operator",
                                "model": "IncidentHistoryItem",
                                "essentialFields": [
                                    "canonicalId",
                                    "severityLevel",
                                    "lifecycleState",
                                    "lastUpdatedAt",
                                ],
                                "optionalFields": [
                                    "sources",
                                    "signalsCount",
                                    "timelineSummary",
                                ],
                            },
                            "zoneDecisionLink": {
                                "endpoint": "/api/zones/{zoneId}/decision?role=operator",
                                "model": "ZoneDecisionView",
                                "essentialFields": ["zone", "risk", "incident"],
                                "optionalFields": ["spread", "routing", "history"],
                            },
                        },
                    },
                    "ZoneDecisionContextView": {
                        "purpose": [
                            "Explain current zone-level risk context",
                            "Show spread, terrain and routing context",
                            "Keep the decision note operator-readable",
                        ],
                        "sections": {
                            "riskSummary": {
                                "endpoint": "/api/zones/{zoneId}/decision?role=operator",
                                "model": "ZoneDecisionView",
                                "essentialFields": ["zone", "risk", "incident"],
                                "optionalFields": [],
                            },
                            "spreadAndRouting": {
                                "endpoint": "/api/zones/{zoneId}/decision?role=operator",
                                "model": "ZoneDecisionView",
                                "essentialFields": ["spread", "routing"],
                                "optionalFields": ["crossConfirmation"],
                            },
                            "historyContext": {
                                "endpoint": "/api/zones/{zoneId}/decision?role=operator",
                                "model": "ZoneDecisionView",
                                "essentialFields": ["history", "note"],
                                "optionalFields": [],
                            },
                        },
                    },
                    "SecondarySituationalPanel": {
                        "purpose": [
                            "Provide compact secondary context without becoming a new workflow",
                        ],
                        "sections": {
                            "selectedIncidentSnapshot": {
                                "endpoint": "/api/incidents/{canonicalId}?role=operator",
                                "model": "IncidentDetailView",
                                "essentialFields": [
                                    "severityLevel",
                                    "lifecycleState",
                                    "status",
                                ],
                                "optionalFields": [
                                    "sources",
                                    "signalsCount",
                                    "timelineSummary",
                                ],
                            },
                            "selectedZoneContext": {
                                "endpoint": "/api/zones/{zoneId}/decision?role=operator",
                                "model": "ZoneDecisionView",
                                "essentialFields": ["spread", "routing", "note"],
                                "optionalFields": ["history", "crossConfirmation"],
                            },
                        },
                    },
                },
                "viewModels": {
                    "IncidentListItem": [
                        "canonicalId",
                        "zoneId",
                        "zoneLabel",
                        "incidentPriority",
                        "status",
                        "lifecycleState",
                        "severityLevel",
                        "spreadPressure",
                        "lastUpdatedAt",
                    ],
                    "IncidentDetailView": [
                        "canonicalId",
                        "runtimeIncidentId",
                        "zoneId",
                        "zoneLabel",
                        "severityLevel",
                        "lifecycleState",
                        "status",
                        "sources",
                        "signalsCount",
                        "timelineSummary",
                    ],
                    "IncidentHistoryItem": [
                        "canonicalId",
                        "zoneId",
                        "zoneLabel",
                        "severityLevel",
                        "lifecycleState",
                        "status",
                        "lastUpdatedAt",
                        "sources",
                        "signalsCount",
                        "timelineSummary",
                    ],
                    "ZoneDecisionView": [
                        "zone",
                        "risk",
                        "incident",
                        "spread",
                        "crossConfirmation",
                        "routing",
                        "history",
                    ],
                    "SituationalCards": [
                        "activeIncidentsCount",
                        "criticalIncidentsCount",
                        "activeCriticalIncidentsCount",
                        "elevatedSpreadIncidentsCount",
                        "containedIncidentsCount",
                        "zonesWithElevatedSpread",
                        "operatorAttentionCount",
                    ],
                },
            },
            "analystExports": {
                "description": "Machine-readable export surfaces for retrospective incident review and external analysis.",
                "requiredEndpoints": [
                    "/api/analyst/incidents",
                    "/api/analyst/incidents/{canonicalId}/bundle",
                    "/api/analyst/incidents/{canonicalId}/history",
                    "/api/analyst/zones/{zoneId}/decision-snapshot",
                ],
                "formats": ["json", "ndjson"],
                "bundles": {
                    "IncidentBundle": [
                        "canonicalId",
                        "zone",
                        "risk",
                        "incident",
                        "spread",
                        "terrainInfluence",
                        "crossConfirmation",
                        "routing",
                        "timeline",
                        "history",
                    ],
                    "ZoneDecisionSnapshot": [
                        "zone",
                        "risk",
                        "spread",
                        "terrainInfluence",
                        "routing",
                        "incident",
                        "crossConfirmation",
                        "history",
                        "note",
                    ],
                    "IncidentHistoryBundle": [
                        "canonicalId",
                        "history",
                    ],
                },
            },
        },
        "endpoints": [
            {
                "path": "/api/zones",
                "method": "GET",
                "description": "List available zones.",
                "roles": [],
                "responseShape": ["id", "label", "region", "location"],
            },
            {
                "path": "/api/zones/{zoneId}/risk",
                "method": "GET",
                "description": "Return minimal zone risk overview with role-aware detail.",
                "roles": roles,
                "responseShape": [
                    "zoneId",
                    "canonicalIncidentId",
                    "incidentPresent",
                    "incidentStatus",
                    "incidentLifecycleState",
                    "incidentSeverityLevel",
                    "spreadPressure",
                    "signalsCount",
                ],
            },
            {
                "path": "/api/incidents",
                "method": "GET",
                "description": "List active incidents from the runtime canonical registry.",
                "roles": roles,
                "responseShape": ["canonicalId", "zoneId", "zoneLabel", "status", "severityLevel", "lifecycleState", "lastUpdatedAt"],
            },
            {
                "path": "/api/incidents/{canonicalId}",
                "method": "GET",
                "description": "Return incident detail with role-aware shaping.",
                "roles": roles,
                "responseShape": [
                    "canonicalId",
                    "zoneId",
                    "zoneLabel",
                    "runtimeIncidentId",
                    "status",
                    "severityLevel",
                    "lifecycleState",
                    "location",
                    "firstObservedAt",
                    "lastUpdatedAt",
                ],
            },
            {
                "path": "/api/incidents/{canonicalId}/history",
                "method": "GET",
                "description": "Return retained persisted history snapshots for one incident.",
                "roles": roles,
                "responseShape": [
                    "canonicalId",
                    "zoneId",
                    "zoneLabel",
                    "status",
                    "severityLevel",
                    "lifecycleState",
                    "lastUpdatedAt",
                    "timeline",
                ],
            },
            {
                "path": "/api/operator/summary",
                "method": "GET",
                "description": "Return compact situational summary cards for the operator dashboard skeleton.",
                "roles": ["operator"],
                "responseShape": [
                    "activeIncidentsCount",
                    "criticalIncidentsCount",
                    "activeCriticalIncidentsCount",
                    "elevatedSpreadIncidentsCount",
                    "containedIncidentsCount",
                    "zonesWithElevatedSpread",
                    "operatorAttentionCount",
                ],
            },
            {
                "path": "/api/analyst/incidents",
                "method": "GET",
                "description": "List current analyst-facing incidents for export or external review.",
                "roles": ["analyst"],
                "responseShape": [
                    "canonicalId",
                    "zoneId",
                    "zoneLabel",
                    "status",
                    "lifecycleState",
                    "severityLevel",
                    "location",
                    "firstObservedAt",
                    "lastUpdatedAt",
                ],
            },
            {
                "path": "/api/analyst/incidents/{canonicalId}/bundle",
                "method": "GET",
                "description": "Export a structured analyst incident bundle.",
                "roles": ["analyst"],
                "responseShape": [
                    "canonicalId",
                    "zone",
                    "risk",
                    "incident",
                    "spread",
                    "terrainInfluence",
                    "crossConfirmation",
                    "routing",
                    "timeline",
                    "history",
                ],
            },
            {
                "path": "/api/analyst/incidents/{canonicalId}/history",
                "method": "GET",
                "description": "Export retained incident history for one canonical incident.",
                "roles": ["analyst"],
                "responseShape": [
                    "canonicalId",
                    "history",
                ],
            },
            {
                "path": "/api/analyst/zones/{zoneId}/decision-snapshot",
                "method": "GET",
                "description": "Export a structured analyst decision snapshot for one zone.",
                "roles": ["analyst"],
                "responseShape": [
                    "zone",
                    "risk",
                    "spread",
                    "terrainInfluence",
                    "routing",
                    "incident",
                    "crossConfirmation",
                    "history",
                    "note",
                ],
            },
            {
                "path": "/api/zones/{zoneId}/decision",
                "method": "GET",
                "description": "Return role-aware decision payload for one zone.",
                "roles": roles,
                "responseShape": ["zone", "risk", "incident", "spread", "routing", "note"],
            },
        ],
    }
